export const hotelCategory = {
  apartment: 'Apartment',
  'bed and breakfast': 'Bed and breakfast',
  boat: 'Boat',
  cabin: 'Cabin',
  camp: 'Camp',
  'holiday home': 'Holiday home',
  hostel: 'Hostel',
  hotel: 'Hotel',
  house: 'House',
  inn: 'Inn',
  'mobile home': 'Mobile home',
  motel: 'Motel',
  other: 'Other',
  spa: 'Spa',
};

export const roomTypeCategory = {
  apartment: 'Apartment',
  barn: 'Barn',
  boat: 'Boat',
  bungalow: 'Bungalow',
  bunk: 'Bunk',
  cabin: 'Cabin',
  condominium: 'Condominium',
  'double or twin room': 'Double or twin room',
  'double room': 'Double room',
  'double room single use': 'Double room single use',
  duplex: 'Duplex',
  lodge: 'Lodge',
  other: 'Other',
  penthouse: 'Penthouse',
  'quadruple room': 'Quadruple room',
  'recreation vehicle': 'Recreation vehicle',
  room: 'Room',
  'shared room': 'Shared room',
  'single room': 'Single room',
  studio: 'Studio',
  suite: 'Suite',
  teepee: 'Teepee',
  tent: 'Tent',
  'tree house': 'Tree house',
  'triple room': 'Triple room',
  'twin room': 'Twin room',
  villa: 'Villa',
  yurt: 'Yurt',
};

export default {
  hotelCategory,
  roomTypeCategory,
};
